### ISSUE TITLE
Relatively wrong dates of death vs alive or relation between CR vs EFS

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/random.cdisc.data#18]
# Original message

First of all I want to state that this issue should not results in any previous wrong analysis results. However I feel that this is important to know about relatively incorrect dates.
There could be observed a relatively wrong dates of death vs alive or relation between CR vs EFS in our random.cdisc.data datasets.
The best description of the issues will be this two print screens:
<REDACTED>user/2704/files/b454e500-a1b0-11ea-9762-ae6d29c425e3)
<REDACTED>user/2704/files/b74fd580-a1b0-11ea-88f3-89d879348ff4)

Provenance: 
```
Creator: Polkas
```

See below https://github.com/insightsengineering/random.cdisc.data/issues/18#issuecomment-1106467364 for example

# TODO

- [ ] in `radsl`, when mutate `DTHDT`, such that if `DTHDT` < `LSTALVDT`, `DTHDT` = `LSTALVDT` + sample(365,1)
- [ ] regenerate `cadsl` and `cadtte`
- [ ] add unittest case and check `DTHDT` > = `LSTALVDT`

#
