### ISSUE TITLE
ADAE: Incorrect Variable Name

### ISSUE THREAD

**Issue by npaszty** [insightsengineering/random.cdisc.data#223]
### What happened?

believe that `ADTHAUT` should be `AEDTHAUT`

found variable in scda.2021 but don't see it in the yaml definition file or in the radae function.

# TODO

Replace `ADTHAUT` to `AEDTHAUT`

### sessionInfo()

```R
don't think this is relevant information for this issue.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by shajoezhu** [comment]
rename `ADTHAUT` to `AEDTHAUT` in adae? what do you think @npaszty

**Comment by npaszty** [comment]
@shajoezhu @edelarua 
right! didn't think to look upstream in ADSL. I guess in this case under the RCD context we just leave it alone.
